name: DemoBlaze Playwright Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ui-tests:
    name: UI Tests (${{ matrix.project }})
    runs-on: ubuntu-latest

    env:
      UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      PAGE_RENDER_TIMEOUT: ${{ secrets.PAGE_RENDER_TIMEOUT }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    strategy:
      matrix:
        project: [chromium, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run UI Login tests
        run: npx playwright test tests/ui/login --project=${{ matrix.project }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: demoblaze-report-ui-${{ matrix.project }}
          path: demoblaze-report/
          retention-days: 7

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    env:
      UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      PAGE_RENDER_TIMEOUT: 5000
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run API tests
        run: npx playwright test tests/api/product  --project=chromium

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: demoblaze-report-api
          path: demoblaze-report/
          retention-days: 7